name: Run Fundaciones Script

on:
  schedule:
    - cron: '0 * * * *' # Ejecuta el script cada hora
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7' # Especifica la versión de Python que necesitas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Asegúrate de tener un archivo requirements.txt con tus dependencias

      - name: Set up Google Sheets credentials
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: |
          echo "${GOOGLE_SHEETS_CREDENTIALS}" > client_secrets.json

      - name: Run Python script
        run: |
          python fundaciones_script.py # Ejecuta tu script Python

      - name: Show generated files
        run: |
          echo "Archivos generados:"
          ls fundaciones/*.html # Muestra los archivos HTML generados

      - name: Check for changes and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add fundaciones/*.html
          if [ -n "$(git diff --cached --name-only)" ]; then
            git commit -m 'Update Fundaciones HTML files from Google Sheets'
            git pull origin main --rebase --strategy-option ours || git merge --strategy-option ours FETCH_HEAD
            git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:main
          else
            echo "No changes to commit."
          fi
